version: "3.9"

services:
  db:
    image: postgres
    container_name: postgresdb
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_HOST_AUTH_METHOD=trust
      - APP_DB_USER=${APP_DB_NAME}
      - APP_DB_PASS=docker
      - APP_DB_NAME=docker
    volumes:
  #- pgdb-data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d/

  levelupworks:
    restart: always
    build: .
    command: > 
      bash -c "python manage.py makemigrations
      && python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    image: levelupworks-image
    container_name: levelupworks-app
    ports:
    - "8000:8000"
    depends_on:
    - db

volumes:
  pgdb-data:
    driver: local