version: "3.9"

services:
  db:
    build:
      #image: postgres
      #container_name: postgresdb
      context: ./Docker
      dockerfile: db.Dockerfile
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_HOST_AUTH_METHOD=trust
      - APP_DB_USER=${APP_DB_NAME}
      - APP_DB_PASS=docker
      - APP_DB_NAME=docker
    volumes:
      - pgdb-data:/var/lib/postgresql/data
      #- pgdb:/docker-entrypoint-initdb.d/
    ports:
      - "6000:5432"

  levelupworks:
    restart: always
    build: .
    command: > 
      bash -c "python manage.py makemigrations
      && python manage.py migrate
      && python manage.py runserver 0.0.0.0:6000"
    volumes:
      - .:/code
    image: levelupworks-image
    container_name: levelupworks-app
    ports:
      - "5432:6000"
    depends_on:
      - db

volumes:
  pgdb-data:
    driver: local