# Generated by Django 3.2.4 on 2021-06-22 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_fname', models.CharField(max_length=100)),
                ('c_lname', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('school', models.CharField(max_length=100)),
                ('level', models.IntegerField()),
                ('heard_from', models.CharField(max_length=100)),
                ('p_fname', models.CharField(max_length=100)),
                ('p_lname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('paid', models.BooleanField(default=True)),
            ],
        ),
    ]
