# Generated by Django 3.2.4 on 2021-06-23 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('levelweb', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='level',
            new_name='term',
        ),
        migrations.RemoveField(
            model_name='student',
            name='paid',
        ),
    ]
