# Generated by Django 3.2.4 on 2021-06-24 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levelweb', '0005_alter_student_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.CharField(max_length=100),
        ),
    ]
